---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"
    checks:
      Generic WhiteSpace DisallowTabIndent TabsUsed:
        enabled: false
      Generic WhiteSpace DisallowTabIndent NonIndentTabsUsed:
        enabled: false
      PSR2 ControlStructures ControlStructureSpacing SpacingAfterOpenBrace:
        enabled: false
      PSR2 ControlStructures ControlStructureSpacing SpaceBeforeCloseBrace:
        enabled: false
      PSR2 Methods FunctionCallSignature SpaceAfterOpenBracket:
        enabled: false
      PSR2 Methods FunctionCallSignature SpaceBeforeCloseBracket:
        enabled: false
      Squiz ControlStructures ForLoopDeclaration SpacingAfterOpen:
        enabled: false
      Squiz ControlStructures ForLoopDeclaration SpacingBeforeClose:
        enabled: false
      Squiz ControlStructures ForEachLoopDeclaration SpaceAfterOpen:
        enabled: false
      Squiz ControlStructures ForEachLoopDeclaration SpaceBeforeClose:
        enabled: false
      Squiz Functions FunctionDeclarationArgumentSpacing SpacingAfterOpen:
        enabled: false
      Squiz Functions FunctionDeclarationArgumentSpacing SpacingBeforeClose:
        enabled: false
      Squiz Functions MultiLineFunctionDeclaration BraceOnSameLine:
        enabled: false
      WordPress VIP RestrictedFunctions get_term_link:
        enabled: false
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseClassName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
- fonts/**/*
- js/jquery.flexslider-min.js
- js/jquery.flexslider.js
- navwalker.php
- js/libs/*
